apiVersion: v1
kind: Pod
metadata:
  name: webapplication
spec:
  containers:
  - name: webapplication-container
    image: wowarjuna/webapplication:latest
  imagePullSecrets:
  - name: dockerhubcred
