name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: List directory
      run: ls
    - name: Setup kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: '<version>' # default is latest stable
      id: install
    - name: Install dependencies
      run: dotnet restore ./WebApplication1/WebApplication1.sln
    - name: Build
      run: dotnet build ./WebApplication1/WebApplication1.sln --configuration Release --no-restore 
  
