name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
  

    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    
    
    - name: install kubectl
      uses: azure/setup-kubectl@v1
    
    - name: Okteto config
      run: |
        mkdir -p ~/.kube/
        cp ./.kube/config/okteto.config ~/.kube/config
        kubectl config view
        kubectl get pod
        
    - name: Set registry on Okteto
      run: kubectl create secret docker-registry dockerhubcred --docker-server=https://index.docker.io/v1/ --docker-username=${{ secrets.DOCKER_HUB_USERNAME }} --docker-password=${{ secrets.DOCKER_HUB_TOKEN }} --docker-email=${{ secrets.DOCKER_HUB_EMAIL }}
