name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
      
    - name: ls
      run: ls ../
        
    - name: install kubectl
      uses: azure/setup-kubectl@v1
    
    - name: kubectl config
      run: kubectl --kubeconfig /Webapplication1/okteto.config config view
             
 

  
