name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
  
    - uses: okteto/login@master
      with:
        token: veYQS4jKLKuW9TTHsQgTUZXpc3WusXrciGhj43PY
    
    - name: "Build"
      uses: okteto/build@master
      with:
        file: ./WebApplication1/WebApplication1/Dockerfile 
        tag: registry.cloud.okteto.net/wowarjuna/weapplication1:dev    
             
 

  
