name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: List directory
      run: ls
    - name: Login to DockerHub updated
      uses: docker/login-action@v1 
      with:
        username: wowarjuna
        password: 2ab3a44c-f7e0-419f-9cd8-7e2d326a82fb
          
    - name: Build and push Docker images
      id: docker_build
      uses: docker/build-push-action@v2.2.1
      with:
        context: ./  
        file: ./WebApplication1/WebApplication1/Dockerfile        
        load: true
        tags: weapplication1:dev    
          
    - name: Push
      run: docker push weapplication1:dev        
             
    - name: Setup kubectl
      uses: azure/setup-kubectl@v1      
      id: install

  
